[workspace]
authors = ["Daniel Claes <dclaes@smart-robotics.nl>"]
channels = ["conda-forge"]
name = "pdf_planner"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.2,<3.15"
